# Knowledge Maker 配置示例文件
# 复制此文件为 config.yml 并根据实际情况修改配置

server:
  port: "8082"
  mode: "release"  # debug, release, test
  allow_domains:
    - "https://example.com"
    - "http://localhost:3000"

ai:
  base_url: "https://api.openai.com/v1"
  api_key: "your-openai-api-key"
  model: "gpt-4"

rag:
  system_prompt: "你是一个专业的知识库助手，请根据提供的上下文信息回答用户问题。"

database:
  type: "sqlite"
  host: "localhost"
  port: 5432
  username: "user"
  password: "password"
  database: "knowledge_maker"

knowledge:
  base_url: "http://localhost:8080"
  token: "your-knowledge-base-token"
  top_k: 3
  vector_db:
    type: "tcvectordb"
    url: "http://localhost:9200"

log:
  dir: "./logs"
  level: "info"
  max_size: 100
  max_backups: 3
  max_age: 28

# 验证码配置 - 支持多种验证码类型
captcha:
  # 验证码类型: "tencent", "geetest", "google_v2", "google_v3", "cloudflare", "aliyun"
  type: "tencent"
  
  # 腾讯云验证码配置
  secret_id: "your-tencent-secret-id"
  secret_key: "your-tencent-secret-key"
  captcha_app_id: 123456789
  app_secret_key: "your-app-secret-key"
  endpoint: "captcha.tencentcloudapi.com"
  captcha_type: 9
  
  # 极验验证码配置
  geetest_id: "your-geetest-id"
  geetest_key: "your-geetest-key"
  geetest_url: "http://gcaptcha4.geetest.com/validate"
  
  # Google reCAPTCHA 配置
  google_recaptcha_site_key: "your-google-site-key"
  google_recaptcha_secret_key: "your-google-secret-key"
  google_recaptcha_url: "https://www.recaptcha.net/recaptcha/api/siteverify"
  google_min_score: 0.5
  
  # Cloudflare Turnstile 配置
  cloudflare_site_key: "your-cloudflare-site-key"
  cloudflare_secret_key: "your-cloudflare-secret-key"
  cloudflare_url: "https://challenges.cloudflare.com/turnstile/v0/siteverify"
  
  # 阿里云验证码配置
  aliyun_access_key_id: "your-aliyun-access-key-id"
  aliyun_access_key_secret: "your-aliyun-access-key-secret"
  aliyun_captcha_app_id: "your-aliyun-captcha-app-id"
  aliyun_endpoint: "captcha-dualstack.cn-shanghai.aliyuncs.com"