# 知识库 RAG 服务配置文件模板
# 复制此文件为 config.yml 并填入真实的配置信息

# 服务器配置
server:
  port: "8082"
  mode: "debug"  # debug, release, test

# AI 服务配置
ai:
  base_url: "https://api.example.com/ai"
  api_key: "your_api_key_here"
  model: "your_model_name"

# 知识库配置
knowledge:
  base_url: "https://api.example.com/knowledge/base/query"
  token: "your_token_here"