# 知识库 RAG 服务配置示例

server:
  port: "8082"
  mode: "release"  # debug, release, test
  allow_domains:
    - "http://localhost:3000"
    - "https://yourdomain.com"

ai:
  base_url: "https://api.openai.com/v1"
  api_key: "your-openai-api-key"
  model: "gpt-3.5-turbo"

rag:
  system_prompt: "你是一个智能助手，请根据提供的知识库内容回答用户问题。"

knowledge:
  base_url: "http://localhost:8080"
  token: "your-knowledge-base-token"
  top_k: 3
  vector_db:
    type: "tcvectordb"
    url: "http://localhost:9200"

database:
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "knowledge_maker"

log:
  dir: "./logs"
  level: "info"
  max_size: 100
  max_backups: 3
  max_age: 28

# 验证码配置
captcha:
  # 验证码类型：tencent（腾讯云）或 geetest（极验） 或 google_v2（Google reCAPTCHA v2）、google_v3（Google reCAPTCHA v3）
  # 留空则不启用验证码
  type: "tencent"
  
  # 腾讯云验证码配置（当 type 为 tencent 时使用）
  secret_id: "your-tencent-cloud-secret-id"
  secret_key: "your-tencent-cloud-secret-key"
  captcha_app_id: 66666666  # 你的验证码应用ID
  app_secret_key: "your-captcha-app-secret-key"  # 验证码应用密钥
  endpoint: "captcha.tencentcloudapi.com"
  captcha_type: 9  # 验证码类型：9为滑动验证码
  
  # 极验验证码配置（当 type 为 geetest 时使用）
  geetest_id: "your-geetest-id"
  geetest_key: "your-geetest-key"
  geetest_url: "http://gcaptcha4.geetest.com/validate"  # 极验验证接口地址

  # Google reCAPTCHA 配置（当 type 为 google_v2 或 google_v3 时使用）
  google_project_id: "intimate-2000"  # Google Cloud 项目 ID
  google_recaptcha_key: "1111111111111111111"  # reCAPTCHA 密钥
  google_min_score: 0.5  # v3 最小分数阈值 (0.0-1.0)