# 知识库 RAG 服务配置文件模板
# 复制此文件为 config.yml 并填入真实的配置信息

# 服务器配置
server:
  port: "8082"
  mode: "debug"  # debug, release, test
  # 支持多个域名配置，留空表示允许所有域名
  allow_domains:
    - "https://www.mintimate.cc"
    - "https://mintimate.cc"

# AI 服务配置
ai:
  base_url: "https://api.example.com/ai"
  api_key: "your_api_key_here"
  model: "your_model_name"

# 知识库配置
knowledge:
  base_url: "https://api.example.com/knowledge/base/query"
  token: "your_token_here"
  top_k: 5


# RAG 服务配置
rag:
  system_prompt: |
    你是 AI 助手，专门检索知识库内的内容，拒绝其他内容（如：情感咨询、数学计算、作文写作和政治主张）。请为用户提供准确的回答。


# 日志配置
log:
  dir: "logs"        # 日志目录
  level: "info"      # 日志级别: debug, info, warn, error
